# Generated by Django 4.1.2 on 2022-10-24 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_gaze', models.CharField(choices=[('ELECTRONICS', 'ELECTRONICS'), ('BOOKS', 'BOOKS'), ('COMPUTERS', 'COMPUTERS')], max_length=50)),
                ('Neg_gaze', models.IntegerField(default=0)),
                ('Pos_control', models.IntegerField(default=0)),
                ('Neg_control', models.IntegerField(default=0)),
                ('Pos_object', models.IntegerField(default=0)),
                ('Neg_object', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
